project:
  type: website
  output-dir: docs
  render:
    -   index.qmd
    -   hospital_analysis.qmd
    -   Project-Model-Selection-Encelia.qmd
    
website:
  title: "CSUF Math Projects"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: hospital_analysis.qmd
        text: "Hospital Analysis"
      - href: Project-Model-Selection-Encelia.qmd
        text: "Encelia Flower Model Selection"
       
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true