project:
  type: website
  output-dir: docs
  render:
    -   index.qmd
    -   Project_1.qmd
    
website:
  title: "CSUF Math Projects"
  navbar:
    left:
#     - href: Index.qmd
#     - text: Home
      - href: Project_1.qmd
        text: "Hospital Analysis"
       
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true